### ISSUE TITLE
Google detects unusual traffic

### ISSUE THREAD

**Issue by lefuglyduck** [meetDeveloper/Dictionary-Anywhere#3] opened 2019-06-27 21:09 UTC
![Screenshot_2019-06-27](https://user-images.githubusercontent.com/31975903/60300759-8605c000-98e4-11e9-9286-c44340b1b1d9.png)

I'm a constant "double clicker" and this is causing me to get this message every time I google something. Maybe only get the definition after selecting a selection bubble?

**Comment by meetDeveloper** [comment] 2019-09-22 05:15
@lefuglyduck Sorry for the inconvenience, I will look into this.

**Comment by meetDeveloper** [comment] 2019-09-26 16:48
@lefuglyduck Actually request never goes to google if you just double click, It goes to fetch data only when you select some text. I checked it again, are you sure this is the only reason that you this error is occurring to you.

**Comment by lefuglyduck** [comment] 2019-09-26 18:03
@meetDeveloper, Actually double clicking on any words in a browser will select the text! Try it.

**Comment by meetDeveloper** [comment] 2019-09-27 02:18
That I know, it was intended to send request to Google on selection of word
so that I can show meaning of the selection, what exactly do you want to
achieve?

**Comment by meetDeveloper** [comment] 2019-09-28 02:10
@lefuglyduck Can you explain this part `Maybe only get the definition after selecting a selection bubble`??

**Comment by lefuglyduck** [comment] 2019-09-28 22:12
For example, after double clicking a word (ie selecting a word), a little pop-up bubble would appear. Only after selecting said bubble would the definition be fetched.

**Comment by meetDeveloper** [comment] 2019-09-29 03:18
@lefuglyduck Actually that will make experience not good, I can give option in which person can assign some key, say suppose ctrl, then whenever he clicks double click + ctrl, then only popup will appear. Will that solve your issue?

**Comment by lefuglyduck** [comment] 2019-09-29 03:24
Yes that would work. Oxford by Oxford Dictionary, has an option as I've described, it's called "display word selection bubble" in the preferences for that extension.

**Comment by meetDeveloper** [comment] 2019-09-29 04:38
@lefuglyduck  Can you give me screenshot how oxford extension does that?

**Comment by lefuglyduck** [comment] 2019-09-29 15:31
![da](https://user-images.githubusercontent.com/31975903/65834797-8622ac80-e293-11e9-9eb4-b6019c423bd5.png)

**Comment by nadesco** [comment] 2019-11-28 01:59
Do you use a VPN? If so then that message you get might be caused by other users on the vpn network all accessing google's servers through one of their servers. I get this message sometimes when going to youtube. If I change servers on the vpn network to one that is not as busy then the message doesn't appear.

**Comment by meetDeveloper** [comment] 2019-12-22 04:32
@lefuglyduck Extension now supports trigger key, which you can enable, then request to google will decrease a lot, and will not go on any double click, can you check and respond if that works for you?

**Comment by meetDeveloper** [comment] 2019-12-22 04:33
What @nadesco says could be a possibility because dictionary anyway never request google unless you select a word which is more than one letter. @lefuglyduck

**Comment by lefuglyduck** [comment] 2019-12-22 06:27
> Do you use a VPN? If so then that message you get might be caused by other users on the vpn network all accessing google's servers through one of their servers. I get this message sometimes when going to youtube. If I change servers on the vpn network to one that is not as busy then the message doesn't appear.

I do use a VPN, but that isn't the issue. I get the "robot" message even when I'm not using the VPN (most of the time).

> Extension now supports trigger key, which you can enable, then request to google will decrease a lot, and will not go on any double click, can you check and respond if that works for you?

Yes, it works again. Thanks.

**Comment by meetDeveloper** [comment] 2019-12-22 07:31
@lefuglyduck Umm, Extension never send request to google if word is not selected, I think problem is somewhere else.

**Comment by meetDeveloper** [comment] 2020-04-22 14:11
Closing this issue as trigger key solved it for the user. cc @lefuglyduck

**Closed by meetDeveloper** 2020-04-22 14:11 UTC
